//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Card
{
	public virtual Count count
	{
		get;
		set;
	}

	public virtual Suit suit
	{
		get;
		set;
	}

	public Card(Count a, Suit b)
	{
	}

	public virtual int BJvalue()
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

