//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Hand
{
	private List<Card> h
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public Hand()
	{
	}

	public virtual void add(Card c)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool remove(Count c, Suit s)
	{
		throw new System.NotImplementedException();
	}

	public virtual int howManyCards()
	{
		throw new System.NotImplementedException();
	}

	public virtual int BJscore()
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

